### ISSUE TITLE
bug: Lazydev has stopped working in directories that are not in a git repo

### ISSUE THREAD

**Issue by maciejzj** [folke/lazydev.nvim#70] opened 2024-10-07 18:29 UTC
### Did you check docs and existing issues?

- [X] I have read all the lazydev.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of lazydev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1727870382

### Operating system/version

MacOS 15.0.1 (24A348)

### Describe the bug

Some time ago (~2 weeks) Lazydev has stopped working in my setup. The `■ Undefined global vim.` diagnostics appear when I open my `init.lua` and features like vim API completions are gone.

I don't think I have changed/updated anything important regarding lazydev in my setup when the problem occurred. I also can't pinpoint any of dependencies (mason, lsp-config, lua ls) to be the source of the problem. I have noticed that the problem disappears when a `.git` directory (be it a real one created by git or a dummy one created manually) is placed alongside `init.lua`.

So far the `.git` thing is the only clue I have found.

Here is my config: https://github.com/maciejzj/dotfiles/blob/cattpuccin/configs/nvim_init.lua

The described behaviour can be reproduced by following the steps below (at least on my computer).

### Steps To Reproduce

1. Make a clean directory and go to it: `user@host:~$ mkdir lazydev-test cd lazydev-test`
2. Copy the minimal `init.lua` provided as `repro.lua` below and place it in the directory: `~/lazydev-test/repro.lua`
3. Open nvim to set up using the `repro.lua` init file: `user@host:~$ nvim -u repro.lua`
4. Wait for stuff to set up (including Mason and lua_ls)
5. Exit nvim `:q`
6. Open `repro.lua` using it as a config at the same time: `user@host:~/lazydev-test$ nvim -u repro.lua repro.lua`
7. Notice that lazydev doesn't work – `■ Undefined global vim.` should appear
8. Exit nvim `:q`
9. Make dummy or real `.git` dir (either `user@host:~/lazydev-test$ mkdir .git` or `user@host:~/lazydev-test$ git init` should do)
10. Reopen the `repro.lua` file: `user@host:~/lazydev-test$ nvim -u repro.lua repro.lua`
11. The errors about `■ Undefined global vim.` should be gone

### Expected Behavior

Lazydev should work and not report `■ Undefined global vim.` regardless of pwd being a git repo or not.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/lazydev.nvim", opts = {} },
    -- add any other plugins here
    "williamboman/mason.nvim",
    "neovim/nvim-lspconfig",
    "williamboman/mason-lspconfig.nvim",
  },
})

local servers = { lua_ls = {} }

require("lazydev").setup()
require("mason").setup()
require("mason-lspconfig").setup({ ensure_installed = vim.tbl_keys(servers) })

local capabilities = vim.lsp.protocol.make_client_capabilities()

require("mason-lspconfig").setup_handlers({
  function(server_name)
    require("lspconfig")[server_name].setup {
      capabilities = capabilities,
      settings = servers[server_name],
      filetypes = (servers[server_name] or {}).filetypes,
    }
  end,
})
```

**Comment by HampusHauffman** [comment] 2024-10-10 16:54
I also have this issue

**Comment by einarpersson** [comment] 2024-10-13 14:03
I can't get this to work so I reverted to neodev for now (which worked out of the box).

```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
```

**Comment by qff233** [comment] 2024-10-13 18:56
May add a line `vim = vim or {}` on the top line?
I found `'vim' is not defined` miss after testing.

**Comment by maciejzj** [comment] 2024-10-13 21:45
@qff233 The plugin doesn't work at all, the `■ Undefined global vim` is just a symptom. If you set `vim = {}`, you may as well not use the plugin at all.

**Comment by dNhKMJnCwqXD** [comment] 2024-10-14 02:26
This problem is caused by this commit in  nvim-lspconfig.
https://github.com/neovim/nvim-lspconfig/commit/814f02ed039ec9fce89949aa4306796b4e14daa5

**Comment by qff233** [comment] 2024-10-14 05:01
@dNhKMJnCwqXD  That is no problem. I rollback `nvim-lspconfig` before https://github.com/neovim/nvim-lspconfig/commit/814f02ed039ec9fce89949aa4306796b4e14daa5. The problem getting `'vim' is not defined` everywhere exist also.

**Comment by qff233** [comment] 2024-10-14 05:23
@maciejzj `vim = vim or {}` is defined in `/usr/shared/nvim/runtime/lua/vim/shared.lua` file.  It is doubtful for me that I can jump to the `vim` in lua runtime of neovim but it just has error `'vim' is not defined` after lines of `vim` everywhere. 
emmmm...
checking the log of lua_ls, I found it is included all lua files under `/usr/shared/nvim/runtime/lua/`. So It is doubtful for me. Every config is no bed. Why do error `'vim' is not defined` appear after lines of 'vim' everywhere? And why do It disappear after I adding a line `vim = vim or {}` at top?

**Comment by dNhKMJnCwqXD** [comment] 2024-10-14 07:59
@qff233 At least in my environment, using the init.lua below fixed the problem.
NVIM v0.10.0
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/lazydev.nvim", opts = {} },
    -- add any other plugins here
    "williamboman/mason.nvim",
    { "neovim/nvim-lspconfig", commit = "8ab8f4cf48425dcb4845a61d3caa2d2a7e3d9df7" },
    "williamboman/mason-lspconfig.nvim",
    "nvim-treesitter/nvim-treesitter",
  },
})

local servers = { lua_ls = {} }

require("lazydev").setup()
require("mason").setup()
require("mason-lspconfig").setup({ ensure_installed = vim.tbl_keys(servers) })

local capabilities = vim.lsp.protocol.make_client_capabilities()

require("mason-lspconfig").setup_handlers({
  function(server_name)
    require("lspconfig")[server_name].setup {
      capabilities = capabilities,
      settings = servers[server_name],
      filetypes = (servers[server_name] or {}).filetypes,
    }
  end,
})

require("nvim-treesitter.configs").setup({
  ensure_installed = { "lua" },
  sync_install = false,
  auto_install = true,
  ignore_install = {},
  modules = {},
})
```

**Comment by maciejzj** [comment] 2024-10-14 08:44
@dNhKMJnCwqXD thanks for finding the root cause of the problem. I can confirm that rolling lspconfig back solves the problem for me, both in the bug reproduction environment as well as in my main setup.

I guess it's up to @folke or someone else well-versed in the ecosystem to decide whether lazydev should have a workaround for this problem, or if something should be changed on lspconfig's side

**Comment by qff233** [comment] 2024-10-14 11:23
@dNhKMJnCwqXD  thanks for finding the root cause of problem. It work fine after removing  `commit` of "neovim/nvim-lspconfig". It need not rolling back!

**Comment by qff233** [comment] 2024-10-14 11:49
I move setting up lsp plugins to init.lua but it still has same problem. Commanding `:LazyDev` to check the library, the library path is not wrong. Why do lsp have error diagnostics?
![图片](https://github.com/user-attachments/assets/07ddde81-6703-469f-8c01-751e7f2ee040)

**Comment by folke** [comment] 2024-10-22 10:38
Will be fixed when https://github.com/neovim/nvim-lspconfig/pull/3391 gets merged. Closing as upstream

**Closed by folke** 2024-10-22 10:38 UTC
Labels: bug
